# Generated by Django 5.2.1 on 2025-05-12 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='users.user'),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='content.educationlevel'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.classlevel'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.subject'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='content.videolesson'),
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='users.user'),
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='content.videolesson'),
        ),
        migrations.AlterUniqueTogether(
            name='videolesson',
            unique_together={('subject', 'class_level', 'order_in_subject')},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'video')},
        ),
        migrations.AlterUniqueTogether(
            name='viewhistory',
            unique_together={('user', 'video')},
        ),
    ]
