# Generated by Django 5.2.1 on 2025-06-13 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='video_id',
            field=models.CharField(default=django.utils.timezone.now, help_text='YouTube video ID or Google Drive file ID', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videolesson',
            name='video_source',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('drive', 'Google Drive')], default='youtube', max_length=20),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
