# Generated by Django 5.2.1 on 2025-06-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_videolesson_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videolesson',
            options={'ordering': ['subject__name', 'class_level__order', 'order_in_subject'], 'permissions': [('can_manage_content', 'Can manage video content')]},
        ),
        migrations.AddField(
            model_name='videolesson',
            name='access_token',
            field=models.CharField(blank=True, help_text='Access token for private/unlisted videos', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video file for direct uploads', null=True, upload_to='videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID or Google Drive file ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='video_source',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('drive', 'Google Drive'), ('upload', 'Direct Upload')], default='youtube', help_text='Source of the video content', max_length=20),
        ),
    ]
