from django.urls import path
from .views import (
    EducationLevelListView, ClassLevelListView, SubjectListView,
    VideoLessonListView, VideoLessonDetailView, VideoLessonCreateView, VideoLessonUpdateView, VideoLessonDeleteView,
    CourseListView, CourseDetailView, CourseBySubjectView, CourseByClassView, FeaturedCourseListView,
    VideoListView, VideoDetailView, VideosByCourseView, VideoProgressView, VideoProgressDetailView, VideoBookmarkView,
    ProgressDashboardView, CourseProgressView, SubjectProgressView, TrackLearningView, RecentActivityView,
    AnalyticsPerformanceView, AnalyticsTimeSpentView, AnalyticsSubjectStrengthsView, AnalyticsRecommendationsView,
    AdminCourseListCreateView, AdminCourseDetailView, AdminVideoListCreateView, AdminVideoDetailView, AdminSubjectListCreateView, AdminSubjectDetailView, AdminClassLevelListView, FreeSampleVideoListView, VideoBookmarksListView, VideoCurrentView,
    AdminVideoUploadView
)

urlpatterns = [
    path('education-levels/', EducationLevelListView.as_view(), name='education-level-list'),
    path('class-levels/', ClassLevelListView.as_view(), name='class-level-list'),
    path('subjects/', SubjectListView.as_view(), name='subject-list'),
    path('lessons/', VideoLessonListView.as_view(), name='lesson-list'),
    path('lessons/<slug:slug>/', VideoLessonDetailView.as_view(), name='lesson-detail'),
    path('lessons/create/', VideoLessonCreateView.as_view(), name='lesson-create'),
    path('lessons/<slug:slug>/update/', VideoLessonUpdateView.as_view(), name='lesson-update'),
    path('lessons/<slug:slug>/delete/', VideoLessonDeleteView.as_view(), name='lesson-delete'),
    path('courses/', CourseListView.as_view(), name='course-list'),
    path('courses/<int:id>/', CourseDetailView.as_view(), name='course-detail'),
    path('courses/subject/<slug:subject>/', CourseBySubjectView.as_view(), name='course-by-subject'),
    path('courses/class/<slug:class_level>/', CourseByClassView.as_view(), name='course-by-class'),
    path('courses/featured/', FeaturedCourseListView.as_view(), name='featured-courses'),
    path('videos/', VideoListView.as_view(), name='video-list'),
    path('videos/<int:id>/', VideoDetailView.as_view(), name='video-detail'),
    path('videos/course/<int:course_id>/', VideosByCourseView.as_view(), name='videos-by-course'),
    path('videos/free-sample/', FreeSampleVideoListView.as_view(), name='free-sample-videos'),
    path('videos/progress/', VideoProgressView.as_view(), name='video-progress'),
    path('videos/progress/<int:id>/', VideoProgressDetailView.as_view(), name='video-progress-detail'),
    path('videos/<int:id>/bookmark/', VideoBookmarkView.as_view(), name='video-bookmark'),
    path('videos/bookmarks/', VideoBookmarksListView.as_view(), name='video-bookmarks'),
    path('videos/current/', VideoCurrentView.as_view(), name='video-current'),
    path('user/bookmarks/', VideoBookmarksListView.as_view(), name='user-bookmarks'),
    path('progress/dashboard/', ProgressDashboardView.as_view(), name='progress-dashboard'),
    path('progress/course/<int:course_id>/', CourseProgressView.as_view(), name='progress-course'),
    path('progress/subject/<int:subject_id>/', SubjectProgressView.as_view(), name='progress-subject'),
    path('progress/track/', TrackLearningView.as_view(), name='progress-track'),
    path('progress/recent-activity/', RecentActivityView.as_view(), name='progress-recent-activity'),
    path('analytics/performance/', AnalyticsPerformanceView.as_view(), name='analytics-performance'),
    path('analytics/time-spent/', AnalyticsTimeSpentView.as_view(), name='analytics-time-spent'),
    path('analytics/subject-strengths/', AnalyticsSubjectStrengthsView.as_view(), name='analytics-subject-strengths'),
    path('analytics/recommendations/', AnalyticsRecommendationsView.as_view(), name='analytics-recommendations'),
    path('admin/courses/', AdminCourseListCreateView.as_view(), name='admin-course-list-create'),
    path('admin/courses/<int:id>/', AdminCourseDetailView.as_view(), name='admin-course-detail'),
    path('admin/videos/upload/', AdminVideoUploadView.as_view(), name='admin-video-upload'),
    path('admin/videos/', AdminVideoListCreateView.as_view(), name='admin-video-list-create'),
    path('admin/videos/<int:id>/', AdminVideoDetailView.as_view(), name='admin-video-detail'),
    path('admin/subjects/', AdminSubjectListCreateView.as_view(), name='admin-subject-list-create'),
    path('admin/subjects/<int:id>/', AdminSubjectDetailView.as_view(), name='admin-subject-detail'),
    path('admin/class-levels/', AdminClassLevelListView.as_view(), name='admin-class-level-list'),
]